[book]
authors = ["howiezhao"]
language = "en"
multilingual = false
src = "src"
title = "programming-terminology"

[output.html]
git-repository-url = "https://github.com/howiezhao/programming-terminology"
